-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.keymaps")
require("plugins.completion")
require("plugins.transparent")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.nullls")
require("plugins.nvim-ipy")
require("plugins.oxacarbon")
require("plugins.openai")
require("plugins.ntree")
